name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

  pull_request:
    paths:
      - 'packages/**'

  workflow_dispatch:
    inputs:
      packages:
        description: "A space-separated names of packages selected for rebuilding"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000

      - name: Prepare Build
        run: |
          ./.github/scripts/prepare.sh

          if [ -f ./built_packages.txt ]
          then
            printf "\nPackages to build:\n"
            cat --number built_packages.txt
          fi
          if [ -f ./deleted_packages.txt ]
          then
            printf "\nPackages to delete:\n"
            cat --number deleted_packages.txt
          fi
        env:
          github_event: ${{ github.event_name }}
          github_inputs_packages: ${{ github.event.inputs.packages }}

      - name: Build
        run: ./.github/scripts/build.sh
        env:
          github_event: ${{ github.event_name }}
          github_inputs_packages: ${{ github.event.inputs.packages }}

      - name: Packages
        if: always()
        run: |
          printf "\n\nPackages Size:\n"
          xz -l ./pkgdest/*//*.xz

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Update file names
        run: |
          for file in ./pkgdest/*/*.pkg.tar*
          do
            new_filename="${file//:/_}"

            if [ "$file" != "$new_filename" ]
            then
              mv "$file" "$new_filename"
            fi
          done

      - name: Sign packages
        if: always() && github.event_name != 'pull_request'
        run: |
          for file in ./pkgdest/*/*.pkg.tar*
          do
            gpg --detach-sign --use-agent --default-key 7A6646A6C14690C0 --batch --yes "$file"
          done

      - name: Upload packages
        if: always() && github.event_name != 'pull_request'
        run: |
          gh release upload queue ./pkgdest/*/*.pkg.tar* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
