name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

  pull_request:
    paths:
      - 'packages/**'

  workflow_dispatch:
    inputs:
      packages:
        description: "A space-separated names of packages selected for rebuilding"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000

      - name: Prepare Build
        run: |
          ./.github/scripts/prepare.sh

          if [ -f ./built_packages.txt ]
          then
            printf "\nPackages to build:\n"
            cat --number built_packages.txt
          fi
          if [ -f ./deleted_packages.txt ]
          then
            printf "\nPackages to delete:\n"
            cat --number deleted_packages.txt
          fi
        env:
          github_event: ${{ github.event_name }}
          github_inputs_packages: ${{ github.event.inputs.packages }}

      - name: Build
        run: ./.github/scripts/build.sh
        env:
          github_event: ${{ github.event_name }}
          github_inputs_packages: ${{ github.event.inputs.packages }}

      - name: Packages
        if: always()
        run: |
          printf "Packages:\n"
          ls -lah pkgs/*.xz

          printf "\n\nPackages Size:\n"
          xz -l pkgs/*.xz

      - name: Upload to Repo
        if: always() && github.event_name != 'pull_request'
        env:
          HTTP_PASSWORD: ${{ secrets.HTTP_PASSWORD }}
          HTTP_USER: ${{ secrets.HTTP_USER }}
          HTTP_URL: ${{ secrets.HTTP_URL }}
        run: |
          ./.github/scripts/upload.sh
