name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

  pull_request:
    paths:
      - 'packages/**'

  workflow_dispatch:
    inputs:
      packages:
        description: "A space-separated names of packages selected for rebuilding"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/archlinux-pkg/packages:latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000

      - name: Prepare Build
        env:
          github_event: ${{ github.event_name }}
          github_inputs_packages: ${{ github.event.inputs.packages }}
        run: |
          ./.github/scripts/build/prepare.sh

          if [ -f ./built_packages.txt ]
          then
            printf "\nPackages to build:\n"
            cat --number built_packages.txt
          fi

          if [ -f ./deleted_packages.txt ]
          then
            printf "\nPackages to delete:\n"
            cat --number deleted_packages.txt
          fi

          sudo chown -R build .

      - name: Delete packages
        if: always() && github.event_name != 'pull_request'
        run: |
          if [ -f ./deleted_packages.txt ]
          then
            su -c '.github/scripts/build/delete-packages.sh $(cat ./deleted_packages.txt)' build
          fi

      - name: Build
        if: always()
        env:
          github_event: ${{ github.event_name }}
          github_inputs_packages: ${{ github.event.inputs.packages }}
        run: |
          if [ -f ./built_packages.txt ]
          then
            su -c '.github/scripts/build/build.sh' build
          fi

      - name: Packages
        if: always()
        run: |
          printf "\n\nPackages Size:\n"
          xz -l ./pkgs/*.xz

      - name: Update file names
        if: always() && github.event_name != 'pull_request'
        run: |
          cd pkgs

          if [ -f medzikuser-mirrorlist-*.pkg.tar.xz ]
          then
            mv medzikuser-mirrorlist-*.pkg.tar.xz medzikuser-mirrorlist.pkg.tar.xz
          fi

          for file in *.pkg.tar*
          do
            new_filename="${file//:/_}"

            if [ "$file" != "$new_filename" ]
            then
              mv "$file" "$new_filename"
            fi
          done

      - name: Import GPG key
        if: always() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Sign packages
        if: always() && github.event_name != 'pull_request'
        run: |
          for file in ./pkgs/*.pkg.tar*
          do
            gpg --detach-sign --use-agent --default-key 7A6646A6C14690C0 --batch --yes "$file"
          done

      - name: Upload packages
        if: always() && github.event_name != 'pull_request'
        env:
          FTP_URI: ${{ secrets.FTP_URI }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_CWD: ${{ secrets.FTP_CWD }}
        run: |
          su -c './.github/scripts/upload.sh' build
