name: Docker image

on:
  push:
    paths:
    - '.github/scripts/docker/**'

  pull_request:
    paths:
    - '.github/scripts/docker/**'

  schedule:
    - cron:  '0 2 * * *'

  workflow_dispatch:

jobs:
  update-packages:
    if: github.repository == 'archlinux-pkg/packages'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.repository == 'archlinux-pkg/packages'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker build --tag "ghcr.io/${{ github.repository_owner }}/packages:latest" ./.github/scripts/docker

      - name: Push image
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.repository == 'archlinux-pkg/packages'
        run: docker push "ghcr.io/${{ github.repository_owner }}/packages:latest"
