name: Package updates

on:
  schedule:
    - cron:  '0 */1 * * *'

  workflow_dispatch:

jobs:
  update-packages:
    if: github.repository == 'archlinux-pkg/packages'
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GH_PUSH_TOKEN }}

      - name: Process package updates
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git config --global user.name "MedzikUserBot"
          git config --global user.email "rm99iv9s@duck.com"
          ./.github/scripts/update-packages.sh
