name: Package updates

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'

  pull_request:
    paths:
      - 'scripts/**'

  schedule:
    - cron:  '*/30 * * * *'

  workflow_dispatch:

jobs:
  update-packages:
    if: github.repository == 'archlinux-pkg/packages'
    runs-on: ubuntu-latest
    container: ghcr.io/archlinux-pkg/packages:latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PUSH_TOKEN }}

      - name: Setup GIT
        run: |
          git config --global user.name "MedzikUserBot"
          git config --global user.email "rm99iv9s@duck.com"

      - name: Install Dependencies
        run: sudo pacman -S --noconfirm npm

      - name: Setup Auto Update Script
        run: npm run setup --prefix ./scripts

      - name: Auto Update
        uses: ./scripts/auto-update
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
