name: Package updates

on:
  schedule:
    - cron:  '0 */1 * * *'

  workflow_dispatch:

jobs:
  update-packages:
    if: github.repository == 'archlinux-pkg/packages'
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_API_KEY }}

    - name: Process package updates
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        ./.github/scripts/update-packages.sh
