name: Rebuild every 12h

on:
  schedule:
    - cron:  '0 */12 * * *'

  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rebuild packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REBUILD }}
        run: ./.github/scripts/rebuild-packages.sh 12h
