name: Trigger rebuild every 12h

on:
  schedule:
    - cron:  '0 */12 * * *'

  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Auto Update Script
        run: npm run setup --prefix ./scripts

      - name: Auto Update
        uses: ./scripts/rebuild
        env:
          token: ${{ secrets.GH_TOKEN_REBUILD }}
          type: 12h
