name: Rebuild every 12h

on:
  schedule:
    - cron:  '0 */12 * * *'

  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Auto Update Script
        run: npm run setup --prefix ./scripts/auto-update

      - name: Auto Update
        uses: ./scripts/auto-update
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          rebuild: 12h
