name: Update repo

on:
  schedule:
    - cron:  '*/30 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/archlinux-pkg/packages:latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download packages
        env:
          FTP_URI: ${{ secrets.FTP_URI }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_CWD: ${{ secrets.FTP_CWD }}
        run: su -c './.github/scripts/download-packages.sh' build

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Repo Add
        env:
          FTP_URI: ${{ secrets.FTP_URI }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_CWD: ${{ secrets.FTP_CWD }}
        run: ./.github/scripts/repo-add.sh

      - name: Upload packages
        env:
          FTP_URI: ${{ secrets.FTP_URI }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_CWD: ${{ secrets.FTP_CWD }}
        run: |
          su -c './.github/scripts/upload.sh' build
