name: Update repo

on:
  # delete this line
  push:

  schedule:
    - cron:  '*/30 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencied
        run: |
          pacman -Sy github-cli

      - name: Download packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/download-packages.sh

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: repo-add
        run: ./.github/scripts/repo-add.sh

      - name: Upload packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload latest ./packages/*.pkg.tar* --clobber
