name: Update repo

on:
  # delete this line
  push:

  schedule:
    - cron:  '*/30 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: medzik/archlinux:latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencied
        run: |
          sudo pacman -Sy github-cli

      - name: Download packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/download-packages.sh

      - name: repo-add
        run: ./.github/scripts/repo-add.sh

      - name: Upload packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload latest ./packages/*.pkg.tar* --clobber
