name: Update repo

on:
  schedule:
    - cron:  '*/15 * * * *'

  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3

      - name: Run in SSH
        env:
          SSHPASS: ${{ secrets.SSHPASS }}
          SSHUSER: ${{ secrets.SSHUSER }}
          SSHHOST: ${{ secrets.SSHHOST }}
        run: ./.github/scripts/update-repo.sh
