name: Update repo

on:
  # delete this line
  push:

  schedule:
    - cron:  '*/30 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/download-packages.sh

      - name: repo-add
        run: |
          sudo docker run \
            --volume $(pwd):/home/archlinux-pkg \
            ghcr.io/archlinux-pkg/packages:latest \
              /home/archlinux-pkg/.github/scripts/repo-add.sh

      - name: Upload packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload latest ./packages/*.pkg.tar* --clobber
